version: '3.8'

services:
  mongo:
    image: mongo:4
    command: --replSet rs0
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/db:/data/db
      - ./docker/mongo/init:/docker-entrypoint-initdb.d:ro
    tty: true

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    depends_on:
      - mongo
    restart: always
